apiVersion: apps/v1
kind: Deployment
metadata:
  name: palpie-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: palpie-app
  template:
    metadata:
      labels:
        app: palpie-app
    spec:
      containers:
        - name: palpie-app
          image: mateusmento/palpie-app:latest
          ports:
            - name: palpie-app-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: palpie-app
spec:
  type: LoadBalancer
  selector:
    app: palpie-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
