apiVersion: apps/v1
kind: Deployment
metadata:
  name: palpie-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: palpie-api
  template:
    metadata:
      labels:
        app: palpie-api
    spec:
      containers:
        - name: palpie-api
          image: mateusmento/palpie-api:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: palpie-api
spec:
  type: LoadBalancer
  selector:
    app: palpie-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
